version: '3'

services:

  postgres:
    image: jwt-auth-postgres
    build:
      context: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3

  app:
    image: jwt-auth
    ports:
    - "8080:8080"
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      DB_HOST: "postgres"