version: '2.1'

services:

  postgres:
    image: jwt-auth-postgres
    build:
      context: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3